### ISSUE TITLE
Wider upload area makes image preview gradient bleed excessively

### ISSUE THREAD

**Issue by dkulchenko** [pqina/filepond-plugin-image-preview#1]
First things first, thanks for the awesome project! So excited to be using it. I noticed something when integrating it into my app:

![screen shot 2018-04-01 at 5 40 03 pm](https://user-images.githubusercontent.com/144206/38179096-d081d8a0-35d3-11e8-87c2-0c18bf90e7e6.png)

It seems the overlay gradient height is somehow based on the width of the overall filepond area, so a narrow drop area like in the examples looks just fine, but place it into a wider div, and the gradient starts to bleed to an extent that the original image is heavily obscured.

**Comment by rikschennink** [comment]
Thanks @dkulchenko glad you like the project!

Yes, the overlay grows relative to the width, but it should be limited, will fix asap. In the meantime, you can add the following style to fix the issue:

```css
.filepond--image-preview-overlay {
    max-height: 7rem;
}
```

**Comment by rikschennink** [comment]
Just published version `1.0.7` of the image preview plugin which should fix this issue.

**Comment by mywebstuff** [comment]
I'm on version 1.0.9 and the issue still persists:
![preview](https://user-images.githubusercontent.com/13365853/38744067-177eb78e-3f41-11e8-9b92-7a60405bcfe9.png)

Setting max-height to 0 kinda solves the problem, although I don't really see what the overlay's job should be? Can you show me a print screen on how it should look? Thanks!

**Comment by mywebstuff** [comment]
Wow, okay sorry, forgot to pull in the CSS file. Can you please add this to the documentation? Thanks!

**Comment by rikschennink** [comment]
@mywebstuff will do!

**Comment by rikschennink** [comment]
@mywebstuff done

**Comment by ephes** [comment]
I'm on 2.0.0 but still get this issue.

**Comment by rikschennink** [comment]
@ephes I've changed the gradients to SVGs in recent update so that might have caused this issue to return, but I believe I checked, will test and get back to you.

**Comment by ephes** [comment]
Thanks for your prompt response, but the temporary style doesn't make a difference for me. I'll just limit the width of the filepond container for now :).

**Comment by rikschennink** [comment]
Odd, in [this codepen](https://codepen.io/rikschennink/pen/XBwpNM?editors=0101) it seems to work, limiting the width will do just fine as well.

**Comment by ephes** [comment]
Weird, maybe it's because I'm using the angular adapter?

**Comment by rikschennink** [comment]
Could be that Angular is wrapping the style in something to make it local to your component? Oh well, fix coming soon :-)

**Comment by ephes** [comment]
I just tested it on my iOS device and noticed that there the overlay is not transparent but solid red/green...

**Comment by rikschennink** [comment]
Oh no, that's not good! I'm on it!

**Comment by rikschennink** [comment]
I can't reproduce the problem, maybe it's a caching issue?

Can you post a screenshot? On which version of iOS is this happening?

**Comment by ephes** [comment]
Tried a different browser, but got the same result. Here's a screenshot:
![img_0548](https://user-images.githubusercontent.com/499500/44152065-adad2afa-a0a4-11e8-8d17-6eca85ff7791.png)

iOS version is 11.4.1

**Comment by rikschennink** [comment]
Is this with the latest version of both FilePond and the Image Preview plugin? If so, can you set up a public test case, I've tried reproducing it on Firefox, Chrome, Safari 11, iOS 12 and iOS 11 but I don't get this error.

**Comment by ephes** [comment]
``` shell
% grep filepond package.json
    "filepond-plugin-file-validate-type": "^1.1.0",
    "filepond-plugin-image-exif-orientation": "^1.0.2",
    "filepond-plugin-image-preview": "^2.0.1",
    "ngx-filepond": "^2.0.6",
```

Is there any way to include the plugins and ngx-filepond from a CDN? I'd like to set up a codepen.

**Comment by ephes** [comment]
I tried to get ngx-filepond to work [on codepen](
https://codepen.io/ephes/pen/XBLpdK), but failed.

Last error message is: "Uncaught TypeError: Cannot read property 'core' of undefined"

**Comment by rikschennink** [comment]
https://codepen.io/rikschennink/pen/vRvZPK

See settings for the CDN. 

I can't imagine this is related to Angular but maybe it is, I would find that very odd, maybe set up a native JS pen?

**Comment by ephes** [comment]
Ok, your codepen works for iOS. I've uploaded my angular app to my server (just the frontend, there's no backend):

http://wersdoerfer.de:8000

Click on use camera.. overlay works in chrome + firefox, but not in safari. Strange..

**Comment by rikschennink** [comment]
No problem, happy to assist! If this is a bug I want to catch it as quickly as possible ;-)

I tried to open the site but it wants me to enter login credentials.

**Comment by ephes** [comment]
Just select use camera from menu or /camera via url, I deactivated authentication..

**Comment by rikschennink** [comment]
Alright, this is super odd, I'm going top run some tests on my local dev environment. It's either a style collision (but I can't really pinpoint what it would be) if it is, it shouldn't happen on my dev environment), or it's a problem with the SVG mask url not being able to access the SVG containing the mask due to it being in a web component?

**Comment by rikschennink** [comment]
I'm not sure why this is happening.

For now, you could try this to disable the gradients:

```css
.filepond svg rect {
    display:none;
}
```

And then render a CSS gradient instead.

```css
.filepond svg {
    background: linear-gradient(rgba(0,0,0,.5), transparent);
}
```

You could wrap these in a CSS selector that targets Safari only.

```css
@supports (-webkit-marquee-repetition: infinite) and (object-fit: fill) {

    /* selectors here */    

}
```

**Comment by ephes** [comment]
Yes, thanks a lot :). This finally worked:

```css
@supports (-webkit-marquee-repetition: infinite) and (object-fit: fill) {
  .filepond--image-preview-overlay svg rect {
    display: none;
  }
  .filepond--image-preview-overlay svg {
    background: linear-gradient(currentColor, transparent);
  }
}
```

But I had to append this to the global styles.css. Component local css didn't work, weird.

**Comment by rikschennink** [comment]
I think local CSS does something to the class names so maybe it mixes it up somehow?

**Comment by ephes** [comment]
Seems to be a [scope issue](https://angular.io/guide/component-styles#style-scope), yup.
